# -*- coding: utf-8 -*-
"""Netflix Analysis using Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13akYkXOGJiNgTihiAmBxc6eaV2MAn3PK

# **Import Libraries and Data**
"""

import numpy as np# linear algebra operations
import pandas as pd# data preparation
import plotly.express as px # for data visualization
from textblob import TextBlob # for sentiment analysis

df = pd.read_csv('netflix_titles.csv')

"""# **Checking Number of Columns and Rows in Data** teks tebal"""

df.shape

df.head()

"""# **Checking Name of The Columns**"""

df.columns

"""# **Making Visualization for The Rating**"""

x = df.groupby('rating').size().reset_index(name='counts')
print(x)

pie_chart = px.pie(x, values='counts', names='rating', title = 'Distribution of content ratings')
pie_chart.show()

"""# **Making Visualization for the Director**"""

df['director'] = df['director'].fillna('Director not specified')
df

directors_list = pd.DataFrame()
print(directors_list)

directors_list = df['director'].str.split(',', expand=True).stack()
print(directors_list)

directors_list = directors_list.to_frame()
print(directors_list)

directors_list.columns = ['Director']
print(directors_list)

directors = directors_list.groupby(['Director']).size().reset_index(name='Total Count')
print(directors)

directors = directors[directors.Director != 'Director not specified']

print(directors)

directors = directors.sort_values(by=['Total Count'], ascending = False)
print(directors)

top5_Directors = directors.head()
print(top5_Directors)

barChart = px.bar(top5_Directors, x = 'Director', y ='Total Count', title='Top 5 Directors on Netflix')
barChart.show()

"""# **Making Visualization for The Casts**"""

df['cast'] = df['cast'].fillna('cast not specified')
df

cast_list = pd.DataFrame()
print(cast_list)

cast_list = df['cast'].str.split(',', expand=True).stack()
print(cast_list)

cast_list = cast_list.to_frame()
print(cast_list)

cast_list.columns = ['Cast']
print(cast_list)

casts = cast_list.groupby(['Cast']).size().reset_index(name='Total Count')
print(casts)

casts = casts[casts.Cast != 'cast not specified']

print(casts)

casts = casts.sort_values(by=['Total Count'], ascending = False)
print(casts)

top5_Casts = casts.head()
print(top5_Casts)

barChart = px.bar(top5_Casts, x = 'Cast', y ='Total Count', title='Top 5 Cast on Netflix')
barChart.show()

df2 = df[['type','release_year']]
df2 = df2.groupby(['type','release_year']).size().reset_index(name='Total Count')
print(df2)